name: CQQ
on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
